# Generated by Django 5.2.16 on 2026-07-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=4, unique=True)),
                ('event_name', models.CharField(max_length=100)),
                ('minimum_team_size', models.PositiveSmallIntegerField(default=1)),
                ('maximum_team_size', models.PositiveSmallIntegerField(default=1)),
                ('registration_fee_type', models.CharField(choices=[('per_participant', 'Per participant'), ('per_team', 'Per team')], default='per_participant', max_length=24)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=250.0, max_digits=8)),
                ('registration_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('is_registration_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_name'],
            },
        ),
    ]
