# Generated by Django 5.2.16 on 2026-07-19 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('team_size', models.PositiveSmallIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('payment_date', models.DateField()),
                ('payment_screenshot_path', models.CharField(max_length=500)),
                ('payment_status', models.CharField(choices=[('pending_verification', 'Pending verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_clarification', 'Needs clarification')], db_index=True, default='pending_verification', max_length=32)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('registration_status', models.CharField(choices=[('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='submitted', max_length=24)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('attendance_marked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_number', models.PositiveSmallIntegerField()),
                ('full_name', models.CharField(max_length=150)),
                ('college_name', models.CharField(max_length=200)),
                ('roll_number', models.CharField(db_index=True, max_length=50)),
                ('mobile_number', models.CharField(db_index=True, max_length=15)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('department', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(max_length=20)),
                ('is_team_leader', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='registrations.registration')),
            ],
            options={
                'ordering': ['participant_number'],
            },
        ),
    ]
