# Generated by Django 5.1.15 on 2026-07-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('razorpay', 'Razorpay')], db_index=True, default='manual', max_length=24),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_screenshot_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
