# Generated by Codex on 2026-08-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("registrations", "0002_registration_payment_order_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_id", models.CharField(db_index=True, max_length=100, unique=True)),
                ("idempotency_key", models.CharField(db_index=True, max_length=64)),
                ("receipt", models.CharField(db_index=True, max_length=40)),
                ("payload_hash", models.CharField(db_index=True, max_length=64)),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("payment_id", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_attempts",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
