# Generated by Codex on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0003_paymentattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="food_preference",
            field=models.CharField(
                choices=[("veg", "Veg"), ("non_veg", "Non-Veg")],
                default="veg",
                max_length=16,
            ),
        ),
    ]
