# Generated by Django 5.1.15 on 2026-08-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_participant_food_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='attendance_marked',
        ),
    ]
