# Generated by Django 5.1.15 on 2026-08-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_remove_attendance_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('cashfree', 'Cashfree')], db_index=True, default='manual', max_length=24),
        ),
    ]
