# Generated by Django 5.1.15 on 2026-08-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_registration_payment_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
