# Generated by Django 5.1.15 on 2026-08-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_alter_participant_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
    ]
