# Generated by Codex on 2026-08-29

from django.db import migrations, models


def normalize_payment_providers(apps, schema_editor):
    registration_model = apps.get_model("registrations", "Registration")
    registration_model.objects.exclude(payment_provider="manual").update(payment_provider="manual")


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0008_alter_registration_email_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentAttempt",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="payment_order_id",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="payment_session_id",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="payment_signature",
        ),
        migrations.RunPython(normalize_payment_providers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="registration",
            name="payment_provider",
            field=models.CharField(
                choices=[("manual", "Manual")],
                db_index=True,
                default="manual",
                max_length=24,
            ),
        ),
    ]
