# Generated by Django 5.1.15 on 2026-08-21 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='password_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
